name: fb_auth_provider
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.5
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  provider: ^6.0.3
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
